#!/bin/bash

# This script records live TV

# Note: RECORD_LENGTH defines the length of the captured video. If the input stream is damaged and frames are lost, they may not count towards the captured video length.

RECORD_DIR=/media/disk/Fernsehen
CHANNEL_NAME=$1
RECORD_PREFIX=$2
RECORD_LENGTH=$3
TIMESTAMP=`date +%Y%m%d%a%H%M`
RECORD_LOGFILE="record_${TIMESTAMP}.log"
#RECORD_LOGFILE="/dev/null"
#RECORD_LOGFILE="/dev/stderr"

# quick and dirty: kill running capture processes
killall ffmpeg
sleep 1
killall czap
sleep 5

cd ${RECORD_DIR}
# try to tune
if czap -H "${CHANNEL_NAME}" 2>/dev/null | head -n 10 | grep -q 'status 1f'
then
  # actually tune
  czap -r "${CHANNEL_NAME}" > /dev/null &
  CZAP_PID=$!
  # record and remux stream
  # mention -f mpegts before -i to define input stream format
  ffmpeg -i /dev/dvb/adapter0/dvr0 -c copy -t ${RECORD_LENGTH} -f mpegts "${CHANNEL_NAME} - ${RECORD_PREFIX} - ${TIMESTAMP}.ts" 2>"${RECORD_LOGFILE}"
  # kill tuner
  kill ${CZAP_PID}
else
  echo "Tuning failed"
  exit 1
fi
