#!/bin/bash

# This script executes a scheduled one-off recording and removes itself from the schedule

CHANNEL_NAME=$1
RECORD_PREFIX=$2
RECORD_LENGTH=$3
HASH=$4


until /usr/local/bin/tv-record "${CHANNEL_NAME}" "${RECORD_PREFIX}" "${RECORD_LENGTH}"
do
  sleep 1m
  # TODO: refine with https://stackoverflow.com/questions/14309032/bash-script-difference-in-minutes-between-two-times
done

if [ "${HASH}" ]
then
  crontab -l | grep -v "${HASH}" | crontab -
fi
